from typing import Any, Iterable, Iterator, Mapping, Sequence, final

from typing_extensions import disjoint_base

__version__: str
LIBMDBX_VERSION: str

MDBX_ENV_DEFAULTS: int
MDBX_VALIDATION: int
MDBX_NOSUBDIR: int
MDBX_RDONLY: int
MDBX_EXCLUSIVE: int
MDBX_ACCEDE: int
MDBX_WRITEMAP: int
MDBX_NOSTICKYTHREADS: int
MDBX_NORDAHEAD: int
MDBX_NOMEMINIT: int
MDBX_LIFORECLAIM: int
MDBX_NOMETASYNC: int
MDBX_SAFE_NOSYNC: int
MDBX_UTTERLY_NOSYNC: int
MDBX_TXN_RDONLY: int
MDBX_TXN_RDONLY_PREPARE: int
MDBX_TXN_TRY: int
MDBX_REVERSEKEY: int
MDBX_DUPSORT: int
MDBX_INTEGERKEY: int
MDBX_DUPFIXED: int
MDBX_INTEGERDUP: int
MDBX_REVERSEDUP: int
MDBX_CREATE: int
MDBX_DB_ACCEDE: int
MDBX_NOOVERWRITE: int
MDBX_NODUPDATA: int
MDBX_CURRENT: int
MDBX_ALLDUPS: int
MDBX_RESERVE: int
MDBX_APPEND: int
MDBX_APPENDDUP: int
MDBX_MULTIPLE: int
MDBX_CP_COMPACT: int
MDBX_CP_FORCE_DYNAMIC_SIZE: int
MDBX_CP_DONT_FLUSH: int
MDBX_CP_THROTTLE_MVCC: int
MDBX_CP_OVERWRITE: int
MDBX_ENV_JUST_DELETE: int
MDBX_ENV_ENSURE_UNUSED: int
MDBX_ENV_WAIT_FOR_UNUSED: int
MDBX_opt_max_db: int
MDBX_opt_max_readers: int
MDBX_opt_sync_bytes: int
MDBX_opt_sync_period: int
MDBX_opt_rp_augment_limit: int
MDBX_opt_loose_limit: int
MDBX_opt_dp_reserve_limit: int
MDBX_opt_txn_dp_limit: int
MDBX_opt_txn_dp_initial: int
MDBX_opt_spill_max_denominator: int
MDBX_opt_spill_min_denominator: int
MDBX_opt_spill_parent4child_denominator: int
MDBX_opt_merge_threshold: int
MDBX_opt_writethrough_threshold: int
MDBX_opt_prefault_write_enable: int
MDBX_opt_gc_time_limit: int
MDBX_opt_prefer_waf_insteadof_balance: int
MDBX_opt_subpage_limit: int
MDBX_opt_subpage_room_threshold: int
MDBX_opt_subpage_reserve_prereq: int
MDBX_opt_subpage_reserve_limit: int
MDBX_opt_split_reserve: int
MDBX_opt_presync_threshold: int
MDBX_warmup_default: int
MDBX_warmup_force: int
MDBX_warmup_oomsafe: int
MDBX_warmup_lock: int
MDBX_warmup_touchlimit: int
MDBX_warmup_release: int
MDBX_defrag_noobstacles: int
MDBX_defrag_step_size: int
MDBX_defrag_large_chunk: int
MDBX_defrag_discontinued: int
MDBX_defrag_laggard_reader: int
MDBX_defrag_enough_threshold: int
MDBX_defrag_time_limit: int
MDBX_defrag_aborted: int
MDBX_defrag_error: int

class Error(Exception):
    what: str
    code: int
    reason: str

class KeyExistsError(Error): ...
class NotFoundError(Error): ...
class PageNotFoundError(Error): ...
class MapFullError(Error): ...
class ReadersFullError(Error): ...
class DbsFullError(Error): ...
class TxnFullError(Error): ...
class CursorFullError(Error): ...
class PageFullError(Error): ...
class UnableExtendMapError(Error): ...
class BadTxnError(Error): ...
class BadDbiError(Error): ...
class BadRslotError(Error): ...
class BadValueSizeError(Error): ...
class BusyError(Error): ...
class CorruptedError(Error): ...
class PanicError(Error): ...
class VersionMismatchError(Error): ...
class InvalidError(Error): ...
class IncompatibleError(Error): ...
class ProblemError(Error): ...
class MultiValueError(Error): ...
class BadSignatureError(Error): ...
class WannaRecoveryError(Error): ...
class KeyMismatchError(Error): ...
class TooLargeError(Error): ...
class ThreadError(Error): ...
class TxnOverlappingError(Error): ...
class BacklogDepletedError(Error): ...
class DuplicatedLockError(Error): ...
class DanglingDbiError(Error): ...
class OustedError(Error): ...
class MvccRetardedError(Error): ...
class LaggardReaderError(Error): ...
class ReadonlyError(Error): ...
class InvalidParameterError(Error): ...
class LockError(Error): ...
class MemoryError(Error): ...
class DiskError(Error): ...
class ForkError(Error): ...
class ClosedError(Error): ...

@disjoint_base
class Environment:
    def __init__(
        self,
        path: Any,
        *,
        flags: int = ...,
        mode: int = ...,
        max_readers: int = ...,
        max_dbs: int = ...,
        geometry: Sequence[int] | None = ...,
        options: Mapping[int, int] | None = ...,
        readonly: bool = ...,
        subdir: bool = ...,
    ) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def path(self) -> Any: ...
    def begin(self, write: bool = ..., parent: Transaction | None = ..., flags: int = ...) -> Transaction: ...
    def read(self) -> Transaction: ...
    def write(self) -> Transaction: ...
    def open_db(self, name: Any = ..., *, flags: int = ..., create: bool = ...) -> Database: ...
    def close(self, *, dont_sync: bool = ...) -> None: ...
    def stat(self) -> dict[str, int]: ...
    def info(self) -> dict[str, Any]: ...
    def sync(self, *, force: bool = ..., nonblock: bool = ...) -> bool: ...
    def copy(self, path: Any, *, flags: int = ...) -> None: ...
    def set_geometry(self, geometry: Sequence[int], /) -> None: ...
    def get_flags(self) -> int: ...
    def set_flags(self, flags: int, *, enabled: bool = ...) -> None: ...
    def get_option(self, option: int, /) -> int: ...
    def set_option(self, option: int, value: int, /) -> None: ...
    def reader_check(self) -> int: ...
    def reap_orphaned_transactions(self) -> int: ...
    def defrag(
        self,
        *,
        at_least_pages: int = ...,
        at_least_time: int = ...,
        enough_pages: int = ...,
        time_limit: int = ...,
        acceptable_backlash: int = ...,
        preferred_batch: int = ...,
    ) -> dict[str, Any]: ...
    def warmup(self, *, flags: int = ..., timeout: int = ...) -> bool: ...
    def __enter__(self) -> Environment: ...
    def __exit__(self, *args: Any) -> None: ...

@final
class Transaction:
    @property
    def id(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def readonly(self) -> bool: ...
    @property
    def active(self) -> bool: ...
    def commit(self) -> None: ...
    def commit_ex(self) -> dict[str, int]: ...
    def abort(self) -> None: ...
    def reset(self) -> None: ...
    def renew(self) -> None: ...
    def break_(self) -> None: ...
    def info(self, *, scan_readers: bool = ...) -> dict[str, Any]: ...
    def refresh(self) -> bool: ...
    def park(self, *, autounpark: bool = ...) -> None: ...
    def unpark(self, *, restart_if_ousted: bool = ...) -> bool: ...
    def canary(self, values: Sequence[int] | None = ...) -> tuple[int, int, int, int]: ...
    def gc_info(self) -> dict[str, Any]: ...
    def databases(self) -> list[dict[str, Any]]: ...
    def open_db(self, name: Any = ..., *, flags: int = ..., create: bool = ..., accede: bool = ...) -> Database: ...
    def cursor(self, db: Database | None = ...) -> Cursor: ...
    def get(self, key: Any, db: Database | None = ..., default: Any = ...) -> Any: ...
    def put(self, key: Any, value: Any, db: Database | None = ..., flags: int = ...) -> bool: ...
    def delete(self, key: Any, value: Any = ..., db: Database | None = ...) -> bool: ...
    def replace(self, key: Any, value: Any, *, db: Database | None = ..., flags: int = ...) -> bytes | None: ...
    def get_many(
        self, keys: Iterable[Any], *, db: Database | None = ..., default: Any = ..., detached: bool = ...
    ) -> list[Any]: ...
    def put_many(
        self, items: Iterable[tuple[Any, Any]], *, db: Database | None = ..., flags: int = ..., detached: bool = ...
    ) -> int: ...
    def delete_many(self, keys: Iterable[Any], *, db: Database | None = ..., detached: bool = ...) -> int: ...
    def stat(self, *, db: Database | None = ...) -> dict[str, int]: ...
    def __getitem__(self, key: Any, /) -> bytes: ...
    def __contains__(self, key: object, /) -> bool: ...
    def __enter__(self) -> Transaction: ...
    def __exit__(self, *args: Any) -> None: ...

@final
class Database:
    @property
    def name(self) -> bytes | None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def stat(self, txn: Transaction, /) -> dict[str, int]: ...
    def flags(self, txn: Transaction, /) -> dict[str, int]: ...
    def clear(self, txn: Transaction, /) -> None: ...
    def drop(self, txn: Transaction, *, delete: bool = ...) -> None: ...
    def sequence(self, txn: Transaction, *, increment: int = ...) -> int: ...
    def rename(self, txn: Transaction, name: Any, /) -> None: ...

@final
class Cursor(Iterator[tuple[bytes, bytes]]):
    def close(self) -> None: ...
    def first(self) -> tuple[bytes, bytes] | None: ...
    def last(self) -> tuple[bytes, bytes] | None: ...
    def next(self) -> tuple[bytes, bytes] | None: ...
    def prev(self) -> tuple[bytes, bytes] | None: ...
    def current(self) -> tuple[bytes, bytes] | None: ...
    def first_dup(self) -> tuple[bytes, bytes] | None: ...
    def last_dup(self) -> tuple[bytes, bytes] | None: ...
    def next_dup(self) -> tuple[bytes, bytes] | None: ...
    def prev_dup(self) -> tuple[bytes, bytes] | None: ...
    def next_nodup(self) -> tuple[bytes, bytes] | None: ...
    def prev_nodup(self) -> tuple[bytes, bytes] | None: ...
    def set(self, key: Any, /) -> tuple[bytes, bytes] | None: ...
    def set_range(self, key: Any, /) -> tuple[bytes, bytes] | None: ...
    def get_both(self, key: Any, value: Any, *, range: bool = ...) -> tuple[bytes, bytes] | None: ...
    def count(self) -> int: ...
    def put(self, key: Any, value: Any, *, flags: int = ...) -> bool: ...
    def delete(self, *, flags: int = ...) -> None: ...
    def renew(self, txn: Transaction, /) -> None: ...
    def items(
        self, *, start: Any = ..., stop: Any = ..., limit: int = ..., reverse: bool = ...
    ) -> list[tuple[bytes, bytes]]: ...
    def __iter__(self) -> Cursor: ...
    def __next__(self) -> tuple[bytes, bytes]: ...
    def __enter__(self) -> Cursor: ...
    def __exit__(self, *args: Any) -> None: ...

def diagnostics() -> dict[str, Any]: ...
def version_info() -> dict[str, Any]: ...
def limits() -> dict[str, int]: ...
def readahead_reasonable(volume: int, redundancy: int = ...) -> bool: ...
def delete_environment(path: Any, mode: int = ...) -> None: ...

open = Environment
